services:
  hookd:
    name: "hook2mqtt"
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - MQTT_HOST
      - MQTT_PORT
      - MQTT_USER
      - MQTT_PASSWORD
      - MQTT_TOPIC_EVENTS
      - MQTT_QOS
      - MQTT_RETAIN
      - DEDUP_SECONDS
      - PRESENCE_TIMEOUT
      - CAMERA_MAP
      - LOG_LEVEL
      - WEBHOOK_TOKEN
    ports:
      - "${PORT:-4040}:8080"
    restart: unless-stopped
